### ISSUE TITLE
Where can I see the Appendix?

### ISSUE THREAD

**Issue by liuxuexun** [vLAR-group/GrowSP#1]
Thanks for your excellent work, your masterpiece impressed me a lot.

I read your paper in CVPR Open Access version, however I can't see the appendix in it which you mention "Implementation details are in Appendix".

Thanks a lot.

**Comment by zhang-zihui** [comment]
@mellody11 , https://openaccess.thecvf.com/content/CVPR2023/supplemental/Zhang_GrowSP_Unsupervised_Semantic_CVPR_2023_supplemental.pdf

**Comment by liuxuexun** [comment]
Thank you~
