### ISSUE TITLE
How many GPUs are needed to complete this experiment, and how much video memory is needed

### ISSUE THREAD

**Issue by mooncakehub** [vLAR-group/GrowSP#12]

**Comment by zhang-zihui** [comment]
@mooncakehub, we use an RTX3090 GPU with 24G memory.

**Comment by mooncakehub** [comment]
thank you for your reply

**Comment by mooncakehub** [comment]
Can your code be multi-GPU parallel

**Comment by zhang-zihui** [comment]
@mooncakehub the training backbone SparseConv can be multi-GPU, but we didn't implement it, you may have a try.
