### ISSUE TITLE
How to Apply a Trained S3DIS Model to a Different Dataset for Inference or Evaluation?

### ISSUE THREAD

**Issue by ome-13** [vLAR-group/GrowSP#14]
"I've trained a model using the S3DIS dataset and obtained a model file (.pth) along with logs stored in the ./ckpt/S3DIS directory. How can I apply this trained model to another dataset for inference or evaluation purposes? What steps or modifications should I make in the code to load this trained model and use it with a different dataset

**Comment by zhang-zihui** [comment]
Hi, @ome-13, you can modify the evaluation code in eval_S3DIS.py, and also modify the dataloader function in https://github.com/vLAR-group/GrowSP/blob/b7eaece0847189c7b94854a03d7a3816bf478236/datasets/S3DIS.py#L208.
I'm not clear your specific evaluation data, you may mimic my code to get a  re-implementation.
