### ISSUE TITLE
About pip install -U MinkowskiEngine --install-option="--blas=openblas" -v --no-deps 

### ISSUE THREAD

**Issue by jing-zhao9** [vLAR-group/GrowSP#7]
Hi,thank you very much for you code,when I encounter issues while executing the command "pip install -U MinkowskiEngine --install-option="--blas=openblas" -v --no-deps"。The error message is as follows:

ERROR: Command errored out with exit status 1: /home/zhaojing/anaconda3/envs/growsp/bin/python3.8 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7uu6ivt6/minkowskiengine_3133980132d24dbc9b1e9acdc4503d1e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7uu6ivt6/minkowskiengine_3133980132d24dbc9b1e9acdc4503d1e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9majr4b7/install-record.txt --single-version-externally-managed --compile --install-headers /home/zhaojing/anaconda3/envs/growsp/include/python3.8/MinkowskiEngine --blas=openblas Check the logs for full command output.

**Comment by zhang-zihui** [comment]
You may try other ways to install MinkowskiEngine, please see https://github.com/NVIDIA/MinkowskiEngine
