### ISSUE TITLE
About Custom DataSet

### ISSUE THREAD

**Issue by yangqu** [vLAR-group/GrowSP#8]
Can I try this on my own data？And I take it that If I would use the kitti data,I have to add the labels.Is the labels obligatory condition?Thank you for your brilliant work

**Comment by zhang-zihui** [comment]
hi @yangqu ,
Labels are not obligatory. However, if you can filter out the "clutter" points, the performances may be better, because our algorithm is a fundamental clustering.

**Comment by yangqu** [comment]
Thank you very much.And I have another question.Due to no model log,I have no idea how much loss I get is proper to say the model is in convergence condition?

**Comment by zhang-zihui** [comment]
@yangqu 
You will see a 'train.log' file in the checkpoint folder when you begin training. This log file records the training loss, kmeans errors and more information.
