### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by yangqu** [vLAR-group/GrowSP#9]
Hi，I have  a try on our custom data.Every frame point cloud is bigger than semantic kitti(two times).It works on semantic kitti with batch-size 8 (My GPU is 3090 12GB mem).But if I use my data,Even though I reduce the batch size to 1 it throws exception:
```
**RuntimeError: CUDA out of memory. Tried to allocate 5.07 GiB (GPU 0; 11.75 GiB total capacity; 5.80 GiB already allocated; 3.20 GiB free; 6.41 
GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF**
```
Can I change other hyperparameters to make it work?

**Comment by zhang-zihui** [comment]
increase the voxel grid size of sparseconv

**Comment by yangqu** [comment]
你好，我这边又遇到了一个问题，就是我发现直接用400的预训练模型，在semanticKitti上结果不佳，是需要设置什么超参数吗，这个是使用你们提供的kitti模型，然后推断08序列里的其中一帧
















At 2023-09-19 13:34:26, "zhang-zihui" ***@***.***> wrote:

increase the voxel grid size of sparseconv

**Comment by zhang-zihui** [comment]
> 你好，我这边又遇到了一个问题，就是我发现直接用400的预训练模型，在semanticKitti上结果不佳，是需要设置什么超参数吗，这个是使用你们提供的kitti模型，然后推断08序列里的其中一帧 At 2023-09-19 13:34:26, "zhang-zihui" ***@***.***> wrote: increase the voxel grid size of sparseconv — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>
请先检查按照默认参数和提供的ckpt，能否复现出文章中接近的结果
